// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa1M1Jmcu5VTAqopD0AeeQfflQLxy6Gf8',
    appId: '1:1004552870785:web:723662b478a06281262680',
    messagingSenderId: '1004552870785',
    projectId: 'evently-app-45dc2',
    authDomain: 'evently-app-45dc2.firebaseapp.com',
    storageBucket: 'evently-app-45dc2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjAHZSORfcb-BfoaVn0PBdEsnFBjkTH70',
    appId: '1:1004552870785:android:b19c09aa0db8f67a262680',
    messagingSenderId: '1004552870785',
    projectId: 'evently-app-45dc2',
    storageBucket: 'evently-app-45dc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNvecg7NQRu8Nz0olhNRthNeOvUzit0L0',
    appId: '1:1004552870785:ios:dd6d0e376219bbbf262680',
    messagingSenderId: '1004552870785',
    projectId: 'evently-app-45dc2',
    storageBucket: 'evently-app-45dc2.firebasestorage.app',
    iosBundleId: 'com.example.eventlyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNvecg7NQRu8Nz0olhNRthNeOvUzit0L0',
    appId: '1:1004552870785:ios:dd6d0e376219bbbf262680',
    messagingSenderId: '1004552870785',
    projectId: 'evently-app-45dc2',
    storageBucket: 'evently-app-45dc2.firebasestorage.app',
    iosBundleId: 'com.example.eventlyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa1M1Jmcu5VTAqopD0AeeQfflQLxy6Gf8',
    appId: '1:1004552870785:web:fbfd8bbca06d0bfb262680',
    messagingSenderId: '1004552870785',
    projectId: 'evently-app-45dc2',
    authDomain: 'evently-app-45dc2.firebaseapp.com',
    storageBucket: 'evently-app-45dc2.firebasestorage.app',
  );
}
